### ISSUE TITLE
Invalid string size

### ISSUE THREAD

**Issue by illudedPerception** [scottanderson/gvas2json#62]
Error: Invalid string size 16777216 at position 0x47f10
Got this error when trying to convert the railroads online v1.0 .sav to .json

save file added 
[PV_main.zip](https://github.com/user-attachments/files/18044171/PV_main.zip)

**Comment by scottanderson** [comment]
Thanks for the report, @illudedPerception. The [gvas](https://github.com/localcc/gvas) library will need to be updated to support the latest format changes.

**Comment by scottanderson** [comment]
Here's a bit more about what's going on:

The `FrameNumberArray` is an `ArrayProperty` containing `TextProperty`s. Inside of the array, there is a sequence of Text objects, most of which are the "None" type (0xff). However, starting at 0x74ef4, there is an `AsNumber` (0x04) type text object. This object is very suspicious, but doesn't immediately cause any parsing errors. When the parser tries to read the next object, it encounters a `Base` (0x00) type text object, which fails to parse because the string length is way too large to be a real string.

![image](https://github.com/user-attachments/assets/141126e3-02b3-4ba3-accd-793e2c32c9ac)

**Comment by illudedPerception** [comment]
i will make a new empty save game and see if i still get the same error when tring to convert, there is a new function in the game where buying 10 rolling stock at once the game automatically assigns numbers to them maybe that is messing something up, though the save game works fine in game

EDIT: so the blank save file works fine, il buy 10 cars and let it auto assign numbers

EDIT#2: well after buying 10 cars and letting the game name them the save will not convert the save file and i get the same error of Error: Invalid string size 16777216 at position 0x1585 a bit different but the cause is known, should it be fixed is up to you

EDIT#3: after deleting the cars with the numbers the save can be converted again

**Comment by scottanderson** [comment]
A fix is up for review here: https://github.com/localcc/gvas/pull/123.

The issue was caused by a missing feature called `TextFormatArgumentData64bitSupport`. This feature allows the `Int` type of `FormatArgumentValue` to use 64-bit values instead of the default 32-bit values. The problem is visible in the second-to-last red box in my screenshot above.

The parser misinterprets a 0-byte in the second red box as signaling the end of the object, but the intended value for that byte is actually `1`, located 4 bytes to the right. This misinterpretation causes the parser to prematurely start reading a new text object before completing the previous one, leading to a failure when parsing the subsequent text object.

**Comment by qq253498229** [comment]
same problem
